/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SuppressionsRouteImport } from './routes/suppressions'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as EmailsIndexRouteImport } from './routes/emails.index'
import { Route as EmailsIdRouteImport } from './routes/emails.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppressionsRoute = SuppressionsRouteImport.update({
  id: '/suppressions',
  path: '/suppressions',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsIndexRoute = EmailsIndexRouteImport.update({
  id: '/emails/',
  path: '/emails/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsIdRoute = EmailsIdRouteImport.update({
  id: '/emails/$id',
  path: '/emails/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/domains': typeof DomainsRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/suppressions': typeof SuppressionsRoute
  '/templates': typeof TemplatesRoute
  '/webhooks': typeof WebhooksRoute
  '/emails/$id': typeof EmailsIdRoute
  '/emails/': typeof EmailsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/domains': typeof DomainsRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/suppressions': typeof SuppressionsRoute
  '/templates': typeof TemplatesRoute
  '/webhooks': typeof WebhooksRoute
  '/emails/$id': typeof EmailsIdRoute
  '/emails': typeof EmailsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/domains': typeof DomainsRoute
  '/keys': typeof KeysRoute
  '/login': typeof LoginRoute
  '/suppressions': typeof SuppressionsRoute
  '/templates': typeof TemplatesRoute
  '/webhooks': typeof WebhooksRoute
  '/emails/$id': typeof EmailsIdRoute
  '/emails/': typeof EmailsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/domains'
    | '/keys'
    | '/login'
    | '/suppressions'
    | '/templates'
    | '/webhooks'
    | '/emails/$id'
    | '/emails/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/domains'
    | '/keys'
    | '/login'
    | '/suppressions'
    | '/templates'
    | '/webhooks'
    | '/emails/$id'
    | '/emails'
  id:
    | '__root__'
    | '/'
    | '/domains'
    | '/keys'
    | '/login'
    | '/suppressions'
    | '/templates'
    | '/webhooks'
    | '/emails/$id'
    | '/emails/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DomainsRoute: typeof DomainsRoute
  KeysRoute: typeof KeysRoute
  LoginRoute: typeof LoginRoute
  SuppressionsRoute: typeof SuppressionsRoute
  TemplatesRoute: typeof TemplatesRoute
  WebhooksRoute: typeof WebhooksRoute
  EmailsIdRoute: typeof EmailsIdRoute
  EmailsIndexRoute: typeof EmailsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppressions': {
      id: '/suppressions'
      path: '/suppressions'
      fullPath: '/suppressions'
      preLoaderRoute: typeof SuppressionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails/': {
      id: '/emails/'
      path: '/emails'
      fullPath: '/emails/'
      preLoaderRoute: typeof EmailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails/$id': {
      id: '/emails/$id'
      path: '/emails/$id'
      fullPath: '/emails/$id'
      preLoaderRoute: typeof EmailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DomainsRoute: DomainsRoute,
  KeysRoute: KeysRoute,
  LoginRoute: LoginRoute,
  SuppressionsRoute: SuppressionsRoute,
  TemplatesRoute: TemplatesRoute,
  WebhooksRoute: WebhooksRoute,
  EmailsIdRoute: EmailsIdRoute,
  EmailsIndexRoute: EmailsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
